import type powerbi from "powerbi-visuals-api";
export interface FossilSettings{backgroundColor:string;padding:number;chartHeight:number;headingSize:number;labelSize:number;scientificSize:number;narrativeSize:number}
export const fossilDefaults:FossilSettings={backgroundColor:"#f4efe5",padding:0,chartHeight:54,headingSize:30,labelSize:14,scientificSize:12,narrativeSize:17};
export function readFossilSettings(dataView?:powerbi.DataView):FossilSettings{const a=dataView?.metadata.objects?.appearance,t=dataView?.metadata.objects?.text;return {backgroundColor:fill(a?.backgroundColor,fossilDefaults.backgroundColor),padding:num(a?.padding,0,0,30),chartHeight:num(a?.chartHeight,54,35,70),headingSize:num(t?.headingSize,30,16,48),labelSize:num(t?.labelSize,14,9,24),scientificSize:num(t?.scientificSize,12,8,20),narrativeSize:num(t?.narrativeSize,17,10,28)};}
export function fossilFormattingModel(s:FossilSettings):powerbi.visuals.FormattingModel{return {cards:[
 {uid:"appearance-card",displayName:"Appearance",groups:[{uid:"surface-group",displayName:"Visual surface",slices:[color("background","Background color",s.backgroundColor),numberAppearance("padding","Internal padding","padding",s.padding),numberAppearance("chart-height","Chart height (%)","chartHeight",s.chartHeight)]}],revertToDefaultDescriptors:desc("appearance",["backgroundColor","padding","chartHeight"])},
 {uid:"text-card",displayName:"Text sizes",groups:[{uid:"text-group",displayName:"Typography",slices:[numberText("heading","Heading","headingSize",s.headingSize),numberText("labels","Group labels","labelSize",s.labelSize),numberText("scientific","Scientific names","scientificSize",s.scientificSize),numberText("narrative","Narrative","narrativeSize",s.narrativeSize)]}],revertToDefaultDescriptors:desc("text",["headingSize","labelSize","scientificSize","narrativeSize"])}
]};}
function fill(value:unknown,fallback:string):string{const v=value as powerbi.Fill|undefined;return v?.solid?.color||fallback;}function num(value:unknown,fallback:number,min:number,max:number):number{return typeof value==="number"&&Number.isFinite(value)?Math.max(min,Math.min(max,value)):fallback;}
function color(uid:string,displayName:string,value:string):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"ColorPicker",properties:{descriptor:{objectName:"appearance",propertyName:"backgroundColor"},value:{value}}}};}function numberAppearance(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"appearance",propertyName},value}}};}function numberText(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"text",propertyName},value}}};}function desc(objectName:string,names:string[]){return names.map(propertyName=>({objectName,propertyName}));}
