/* eslint-disable powerbi-visuals/no-inner-outer-html */
import type powerbi from "powerbi-visuals-api";
import * as d3 from "d3";
import { fossilDefaults, fossilFormattingModel, readFossilSettings } from "./settings";
import "../style/visual.css";
type Row={period:string;scientific:string;common:string;count:number;leader:string;share:number;leaderSummary:string;periodSummary:string};
const colors:Record<string,string>={Trilobita:'#657f76',Brachiopoda:'#9b603f',Bryozoa:'#7d7462',Anthozoa:'#b24b3b',Crinoidea:'#7e6994',Bivalvia:'#287d83',Gastropoda:'#bd8533',Ammonoidea:'#385d86',Echinoidea:'#879745'};
export class Visual implements powerbi.extensibility.visual.IVisual{
  private root:HTMLDivElement;private svg:d3.Selection<SVGSVGElement,unknown,null,undefined>;private width=500;private height=360;
  private settings={...fossilDefaults};
  constructor(options?:powerbi.extensibility.visual.VisualConstructorOptions){if(!options) throw new Error("Power BI must supply visual constructor options.");this.root=document.createElement("div");this.root.className="fossil-root";this.root.innerHTML='<header><h2>Marine fossil occurrences</h2><span id="period"></span></header><div class="chart"><svg aria-label="Marine fossil occurrences by group"></svg></div><section class="narrative"><div class="stat"><strong id="share">—</strong><span>of selected records</span></div><div class="story"><p><b id="leader"></b><span id="leaderSentence"></span></p><p id="periodSummary"></p></div></section>';options.element.appendChild(this.root);this.svg=d3.select(this.root).select("svg");}
  public update(options:powerbi.extensibility.visual.VisualUpdateOptions):void{
    this.settings=readFossilSettings(options.dataViews?.[0]);this.applySettings();this.width=Math.max(300,options.viewport.width);this.height=Math.max(180,(options.viewport.height-52)*(this.settings.chartHeight/100));const table=options.dataViews?.[0]?.table;
    if(!table?.rows?.length){this.showEmpty();return;}const ix=(role:string)=>table.columns.findIndex(c=>Boolean(c.roles?.[role]));
    const rows:Row[]=table.rows.map(r=>({period:String(r[ix("period")]??""),scientific:String(r[ix("scientificName")]??""),common:String(r[ix("commonName")]??""),count:Number(r[ix("occurrenceCount")]),leader:String(r[ix("leaderName")]??""),share:Number(r[ix("leaderShare")]),leaderSummary:String(r[ix("leaderSummary")]??""),periodSummary:String(r[ix("periodSummary")]??"")})).filter(r=>r.scientific&&Number.isFinite(r.count)).sort((a,b)=>d3.descending(a.count,b.count));
    if(!rows.length){this.showEmpty();return;}const meta=rows[0],pct=d3.format('.0%')(meta.share);
    (this.root.querySelector('#period') as HTMLElement).textContent=meta.period;(this.root.querySelector('#share') as HTMLElement).textContent=pct;(this.root.querySelector('#leader') as HTMLElement).textContent=meta.leader;(this.root.querySelector('#leaderSentence') as HTMLElement).textContent=meta.leaderSummary.slice(meta.leader.length);(this.root.querySelector('#periodSummary') as HTMLElement).textContent=meta.periodSummary;this.render(rows);
  }
  public getFormattingModel():powerbi.visuals.FormattingModel{return fossilFormattingModel(this.settings);}
  private applySettings():void{const s=this.settings,root=document.documentElement;root.style.setProperty("--visual-bg",s.backgroundColor);this.root.style.setProperty("--heading-size",`${s.headingSize}px`);this.root.style.setProperty("--label-size",`${s.labelSize}px`);this.root.style.setProperty("--scientific-size",`${s.scientificSize}px`);this.root.style.setProperty("--narrative-size",`${s.narrativeSize}px`);this.root.style.padding=`${s.padding}px`;this.root.style.gridTemplateRows=`52px ${s.chartHeight}% 1fr`;}
  private showEmpty():void{this.svg.selectAll('*').remove();(this.root.querySelector('#period') as HTMLElement).textContent='Add the fossil fields';(this.root.querySelector('#share') as HTMLElement).textContent='—';(this.root.querySelector('#leader') as HTMLElement).textContent='';(this.root.querySelector('#leaderSentence') as HTMLElement).textContent='';(this.root.querySelector('#periodSummary') as HTMLElement).textContent='';}
  private render(rows:Row[]):void{
    const W=this.width,H=this.height,m={top:18,right:48,bottom:28,left:170};this.svg.attr('viewBox',`0 0 ${W} ${H}`).selectAll('*').remove();const x=d3.scaleLinear().domain([0,d3.max(rows,d=>d.count)??1]).nice().range([m.left,W-m.right]),y=d3.scaleBand().domain(rows.map(d=>d.scientific)).range([m.top,H-m.bottom]).padding(.12);
    this.svg.append('g').attr('class','grid').attr('transform',`translate(0,${H-m.bottom})`).call(d3.axisBottom(x).ticks(4).tickSize(-(H-m.top-m.bottom)).tickFormat(d3.format('~s')));const g=this.svg.append('g').selectAll('g').data(rows).join('g');g.append('rect').attr('x',m.left).attr('y',d=>y(d.scientific)!).attr('height',y.bandwidth()).attr('width',d=>x(d.count)-m.left).attr('fill',d=>colors[d.scientific]||'#777');const labels=g.append('text').attr('class','bar-label').attr('x',m.left-10).attr('text-anchor','end');labels.each(function(d){const common=wrapLabel(d.common,18),lineHeight=13,start=(y(d.scientific)??0)+y.bandwidth()/2-((common.length)*lineHeight)/2+4,text=d3.select(this);common.forEach((line,i)=>text.append('tspan').attr('x',m.left-10).attr('y',start+i*lineHeight).text(line));text.append('tspan').attr('class','scientific-label').attr('x',m.left-10).attr('y',start+common.length*lineHeight).text(d.scientific);});g.append('text').attr('class','bar-value').attr('x',d=>x(d.count)+6).attr('y',d=>y(d.scientific)!+y.bandwidth()/2+4).text(d=>d3.format(',')(d.count));
  }
}

function wrapLabel(value:string,max:number):string[]{const words=value.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(next.length>max&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);return lines;}
