import powerbi from "powerbi-visuals-api";
export interface DetailSettings{backgroundColor:string;normalColor:string;watchColor:string;alertColor:string;padding:number;panelLabelSize:number;statusSize:number;systemSize:number;headingSize:number;descriptionSize:number;metricLabelSize:number;metricSize:number;metricCaptionSize:number;narrativeSize:number;emptySize:number}
export const detailDefaults:DetailSettings={backgroundColor:"#091117",normalColor:"#24e2d3",watchColor:"#ffc35c",alertColor:"#ff6259",padding:0,panelLabelSize:13,statusSize:13,systemSize:13,headingSize:34,descriptionSize:16,metricLabelSize:12,metricSize:28,metricCaptionSize:11,narrativeSize:15,emptySize:16};
export function readDetailSettings(view?:powerbi.DataView):DetailSettings{const a=view?.metadata.objects?.appearance,t=view?.metadata.objects?.text;return{backgroundColor:fill(a?.backgroundColor,detailDefaults.backgroundColor),normalColor:fill(a?.normalColor,detailDefaults.normalColor),watchColor:fill(a?.watchColor,detailDefaults.watchColor),alertColor:fill(a?.alertColor,detailDefaults.alertColor),padding:num(a?.padding,0,24,0),panelLabelSize:num(t?.panelLabelSize,9,24,detailDefaults.panelLabelSize),statusSize:num(t?.statusSize,9,24,detailDefaults.statusSize),systemSize:num(t?.systemSize,9,24,detailDefaults.systemSize),headingSize:num(t?.headingSize,18,52,detailDefaults.headingSize),descriptionSize:num(t?.descriptionSize,10,28,detailDefaults.descriptionSize),metricLabelSize:num(t?.metricLabelSize,9,24,detailDefaults.metricLabelSize),metricSize:num(t?.metricSize,14,42,detailDefaults.metricSize),metricCaptionSize:num(t?.metricCaptionSize,9,22,detailDefaults.metricCaptionSize),narrativeSize:num(t?.narrativeSize,10,28,detailDefaults.narrativeSize),emptySize:num(t?.emptySize,10,28,detailDefaults.emptySize)};}
export function detailFormattingModel(s:DetailSettings):powerbi.visuals.FormattingModel{return{cards:[
 {uid:"appearance-card",displayName:"Appearance",groups:[{uid:"surface",displayName:"Visual surface",slices:[color("background","Background color","backgroundColor",s.backgroundColor),color("normal","Normal color","normalColor",s.normalColor),color("watch","Watch color","watchColor",s.watchColor),color("alert","Alert color","alertColor",s.alertColor),numberAppearance("padding","Internal padding","padding",s.padding)]}],revertToDefaultDescriptors:desc("appearance",["backgroundColor","normalColor","watchColor","alertColor","padding"])},
 {uid:"text-card",displayName:"Text sizes",groups:[
  {uid:"header-text",displayName:"Assembly header",slices:[numberText("panel-label","Panel label","panelLabelSize",s.panelLabelSize),numberText("status","Status","statusSize",s.statusSize),numberText("system","System label","systemSize",s.systemSize),numberText("heading","Assembly heading","headingSize",s.headingSize)]},
  {uid:"metric-text",displayName:"Metrics",slices:[numberText("metric-label","Metric labels","metricLabelSize",s.metricLabelSize),numberText("metric","Metric values","metricSize",s.metricSize),numberText("metric-caption","Metric captions","metricCaptionSize",s.metricCaptionSize)]},
  {uid:"narrative-text",displayName:"Descriptions",slices:[numberText("description","Description","descriptionSize",s.descriptionSize),numberText("narrative","Narrative","narrativeSize",s.narrativeSize),numberText("empty","Empty-state message","emptySize",s.emptySize)]}
 ],revertToDefaultDescriptors:desc("text",["panelLabelSize","statusSize","systemSize","headingSize","descriptionSize","metricLabelSize","metricSize","metricCaptionSize","narrativeSize","emptySize"])}
]};}
function color(uid:string,displayName:string,propertyName:string,value:string):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"ColorPicker",properties:{descriptor:{objectName:"appearance",propertyName},value:{value}}}};}
function numberAppearance(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"appearance",propertyName},value}}};}
function numberText(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"text",propertyName},value}}};}
function desc(objectName:string,names:string[]){return names.map(propertyName=>({objectName,propertyName}));}
function fill(value:powerbi.DataViewPropertyValue|undefined,fallback:string):string{const f=value as powerbi.Fill|undefined;return f?.solid?.color||fallback;}
function num(value:powerbi.DataViewPropertyValue|undefined,min:number,max:number,fallback:number):number{const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
