import type powerbi from "powerbi-visuals-api";
export interface GlobeSettings{backgroundColor:string;padding:number;landColor:string;oceanColor:string;headingSize:number;snapshotSize:number;narrativeSize:number}
export const globeDefaults:GlobeSettings={backgroundColor:"#f4efe5",padding:0,landColor:"#b76239",oceanColor:"#dbeae7",headingSize:30,snapshotSize:31,narrativeSize:16};
export function readGlobeSettings(dataView?:powerbi.DataView):GlobeSettings{const a=dataView?.metadata.objects?.appearance,t=dataView?.metadata.objects?.text;return {backgroundColor:fill(a?.backgroundColor,globeDefaults.backgroundColor),padding:num(a?.padding,0,0,30),landColor:fill(a?.landColor,globeDefaults.landColor),oceanColor:fill(a?.oceanColor,globeDefaults.oceanColor),headingSize:num(t?.headingSize,30,16,48),snapshotSize:num(t?.snapshotSize,31,16,48),narrativeSize:num(t?.narrativeSize,16,10,28)};}
export function globeFormattingModel(s:GlobeSettings):powerbi.visuals.FormattingModel{return {cards:[
 {uid:"appearance-card",displayName:"Appearance",groups:[{uid:"surface-group",displayName:"Visual surface",slices:[color("background","Background color","backgroundColor",s.backgroundColor),numSlice("padding","Internal padding","padding",s.padding),color("land","Land color","landColor",s.landColor),color("ocean","Ocean color","oceanColor",s.oceanColor)]}],revertToDefaultDescriptors:desc("appearance",["backgroundColor","padding","landColor","oceanColor"])},
 {uid:"text-card",displayName:"Text sizes",groups:[{uid:"text-group",displayName:"Typography",slices:[numText("heading","Heading","headingSize",s.headingSize),numText("snapshot","Snapshot label","snapshotSize",s.snapshotSize),numText("narrative","Narrative","narrativeSize",s.narrativeSize)]}],revertToDefaultDescriptors:desc("text",["headingSize","snapshotSize","narrativeSize"])}
]};}
function fill(value:unknown,fallback:string):string{const v=value as powerbi.Fill|undefined;return v?.solid?.color||fallback;}function num(value:unknown,fallback:number,min:number,max:number):number{return typeof value==="number"&&Number.isFinite(value)?Math.max(min,Math.min(max,value)):fallback;}
function color(uid:string,displayName:string,propertyName:string,value:string):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"ColorPicker",properties:{descriptor:{objectName:"appearance",propertyName},value:{value}}}};}function numSlice(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"appearance",propertyName},value}}};}function numText(uid:string,displayName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return {uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName:"text",propertyName},value}}};}function desc(objectName:string,names:string[]){return names.map(propertyName=>({objectName,propertyName}));}
