import powerbi from "powerbi-visuals-api";
export interface SelectorSettings{backgroundColor:string;selectedColor:string;padding:number;showHeading:boolean;showControls:boolean;motion:boolean;headingSize:number;subtitleSize:number;controlSize:number;hintSize:number;bindingSize:number;tooltipTitleSize:number;tooltipBodySize:number}
export const selectorDefaults:SelectorSettings={backgroundColor:"#05080c",selectedColor:"#24e2d3",padding:0,showHeading:true,showControls:true,motion:true,headingSize:24,subtitleSize:13,controlSize:14,hintSize:13,bindingSize:15,tooltipTitleSize:17,tooltipBodySize:14};
export function readSelectorSettings(view?:powerbi.DataView):SelectorSettings{const a=view?.metadata.objects?.appearance,b=view?.metadata.objects?.behavior,t=view?.metadata.objects?.text;return{backgroundColor:fill(a?.backgroundColor,selectorDefaults.backgroundColor),selectedColor:fill(a?.selectedColor,selectorDefaults.selectedColor),padding:num(a?.padding,0,24,0),showHeading:bool(b?.showHeading,true),showControls:bool(b?.showControls,true),motion:bool(b?.motion,true),headingSize:num(t?.headingSize,14,40,selectorDefaults.headingSize),subtitleSize:num(t?.subtitleSize,9,24,selectorDefaults.subtitleSize),controlSize:num(t?.controlSize,9,24,selectorDefaults.controlSize),hintSize:num(t?.hintSize,9,24,selectorDefaults.hintSize),bindingSize:num(t?.bindingSize,10,28,selectorDefaults.bindingSize),tooltipTitleSize:num(t?.tooltipTitleSize,10,28,selectorDefaults.tooltipTitleSize),tooltipBodySize:num(t?.tooltipBodySize,9,24,selectorDefaults.tooltipBodySize)};}
export function selectorFormattingModel(s:SelectorSettings):powerbi.visuals.FormattingModel{return{cards:[
 {uid:"appearance-card",displayName:"Appearance",groups:[{uid:"surface",displayName:"Visual surface",slices:[color("background","Background color","backgroundColor",s.backgroundColor),color("selection","Selection glow","selectedColor",s.selectedColor),numberSlice("padding","Internal padding","appearance","padding",s.padding)]}],revertToDefaultDescriptors:desc("appearance",["backgroundColor","selectedColor","padding"])},
 {uid:"behavior-card",displayName:"Behavior",groups:[{uid:"behavior",displayName:"Interaction",slices:[toggle("heading","Show heading","showHeading",s.showHeading),toggle("controls","Show controls","showControls",s.showControls),toggle("motion","Animate rotors","motion",s.motion)]}],revertToDefaultDescriptors:desc("behavior",["showHeading","showControls","motion"])},
 {uid:"text-card",displayName:"Text sizes",groups:[
  {uid:"primary-text",displayName:"Heading and controls",slices:[numberSlice("heading-size","Heading","text","headingSize",s.headingSize),numberSlice("subtitle-size","Heading subtitle","text","subtitleSize",s.subtitleSize),numberSlice("control-size","Control buttons","text","controlSize",s.controlSize),numberSlice("hint-size","Interaction hint","text","hintSize",s.hintSize)]},
  {uid:"message-text",displayName:"Messages and tooltips",slices:[numberSlice("binding-size","Data binding message","text","bindingSize",s.bindingSize),numberSlice("tooltip-title-size","Tooltip title","text","tooltipTitleSize",s.tooltipTitleSize),numberSlice("tooltip-body-size","Tooltip details","text","tooltipBodySize",s.tooltipBodySize)]}
 ],revertToDefaultDescriptors:desc("text",["headingSize","subtitleSize","controlSize","hintSize","bindingSize","tooltipTitleSize","tooltipBodySize"])}
]};}
function color(uid:string,displayName:string,propertyName:string,value:string):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"ColorPicker",properties:{descriptor:{objectName:"appearance",propertyName},value:{value}}}};}
function numberSlice(uid:string,displayName:string,objectName:string,propertyName:string,value:number):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"NumUpDown",properties:{descriptor:{objectName,propertyName},value}}};}
function toggle(uid:string,displayName:string,propertyName:string,value:boolean):powerbi.visuals.FormattingSlice{return{uid,displayName,control:{type:"ToggleSwitch",properties:{descriptor:{objectName:"behavior",propertyName},value}}};}
function desc(objectName:string,names:string[]){return names.map(propertyName=>({objectName,propertyName}));}
function fill(value:powerbi.DataViewPropertyValue|undefined,fallback:string):string{const f=value as powerbi.Fill|undefined;return f?.solid?.color||fallback;}
function num(value:powerbi.DataViewPropertyValue|undefined,min:number,max:number,fallback:number):number{const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function bool(value:powerbi.DataViewPropertyValue|undefined,fallback:boolean):boolean{return typeof value==="boolean"?value:fallback;}
